### ISSUE TITLE
Hi, How I can use this code for my own images dataset

### ISSUE THREAD

**Issue by sousoufa** [avilash/pytorch-siamese-triplet#1]

**Comment by avilash** [comment]
Currently, the process is not easy to add a new dataset. Will try to add that functionality and make it smooth ASAP

**Comment by sousoufa** [comment]
Thank you

**Comment by avilash** [comment]
Hello @sousoufa 
Have added instructions in the readme to train on custom datasets

**Comment by sousoufa** [comment]
Thank you
Envoyé depuis Yahoo Mail pour Android 
 
  Le dim., juil. 19, 2020 à 1:41, Avilash Kumar<notifications@github.com> a écrit :   


Hello @sousoufa
Have added instructions in the readme to train on custom datasets

**Comment by sousoufa** [comment]
Thank you
